site_name: ts_utils 
site_url: https://devjeetrr.github.io/ts_utils/
repo_url: https://github.com/devjeetr/ts_utils

theme: 
  name: material
  font:
    code: Fira Code
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstrings_section_style: "list"

# nav:
#   - Overview: "README.md"
#   - 'API Reference':
#     - 'General Utilities': "api/general.md"
#     - 'Traversals': "api/traversals.md"
#     - 'Language Library Management': "api/language_utils.md"
      

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


watch:
  - ts_utils

