[tool.poetry]
name = "ts_utils"
version = "0.1.0"
description = ""
authors = ["Devjeet Roy <devjeetrr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
tree-sitter = "^0.19.0"
tqdm = "^4.62.3"
GitPython = "^3.1.24"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
yapf = "^0.31.0"
jupyter = "^1.0.0"
notebook = "^6.4.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
